#!/bin/bash

# 修改默认IP
# sed -i 's/192.168.1.1/10.0.0.1/g' package/base-files/files/bin/config_generate

# 修改主机名称
# sed -i 's/ImmortalWrt/K2P-A2/g' package/base-files/files/bin/config_generate

# 修改默认wifi名称ssid为tymishop
# sed -i 's/ssid=OpenWrt/ssid=tymishop/g' package/kernel/mac80211/files/lib/wifi/mac80211.sh

#开启MU-MIMO
# sed -i 's/mu_beamformer=0/mu_beamformer=1/g' package/kernel/mac80211/files/lib/wifi/mac80211.sh

#wifi加密方式，没有是none
# sed -i 's/encryption=none/encryption=psk2/g' package/kernel/mac80211/files/lib/wifi/mac80211.sh

#wifi密码
# sed -i 's/key=15581822425/key=gds.2021/g' package/kernel/mac80211/files/lib/wifi/mac80211.sh

sed -i -E 's/CONFIG_IB=(m|y)/# CONFIG_IB is not set/' .config
sed -i -E 's/CONFIG_JSON_CYCLONEDX_SBOM=(m|y)/# CONFIG_JSON_CYCLONEDX_SBOM is not set/' .config
sed -i -E 's/CONFIG_SDK=(m|y)/# CONFIG_SDK is not set/' .config
sed -i -E 's/CONFIG_SDK_LLVM_BPF=(m|y)/# CONFIG_SDK_LLVM_BPF is not set/' .config
sed -i -E 's/CONFIG_MAKE_TOOLCHAIN=(m|y)/# CONFIG_MAKE_TOOLCHAIN is not set/' .config
sed -i -E 's/CONFIG_COLLECT_KERNEL_DEBUG=(m|y)/# CONFIG_COLLECT_KERNEL_DEBUG is not set/' .config

sed -i -E 's/CONFIG_PACKAGE_dnsmasq-full=(m|y)/# CONFIG_PACKAGE_dnsmasq-full is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_dnsmasq_full_dhcp=(m|y)/# CONFIG_PACKAGE_dnsmasq_full_dhcp is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_dnsmasq_full_dhcpv6=(m|y)/# CONFIG_PACKAGE_dnsmasq_full_dhcpv6 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_dnsmasq_full_dnssec=(m|y)/# CONFIG_PACKAGE_dnsmasq_full_dnssec is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_dnsmasq_full_auth=(m|y)/# CONFIG_PACKAGE_dnsmasq_full_auth is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_dnsmasq_full_nftset=(m|y)/# CONFIG_PACKAGE_dnsmasq_full_nftset is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_dnsmasq_full_conntrack=(m|y)/# CONFIG_PACKAGE_dnsmasq_full_conntrack is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_dnsmasq_full_noid=(m|y)/# CONFIG_PACKAGE_dnsmasq_full_noid is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_dnsmasq_full_tftp=(m|y)/# CONFIG_PACKAGE_dnsmasq_full_tftp is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_firewall4=(m|y)/# CONFIG_PACKAGE_firewall4 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_procd-ujail=(m|y)/# CONFIG_PACKAGE_procd-ujail is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_qosify=(m|y)/# CONFIG_PACKAGE_qosify is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_ar3k-firmware=(m|y)/# CONFIG_PACKAGE_ar3k-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_ath9k-htc-firmware=(m|y)/# CONFIG_PACKAGE_ath9k-htc-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_bnx2-firmware=(m|y)/# CONFIG_PACKAGE_bnx2-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_bnx2x-firmware=(m|y)/# CONFIG_PACKAGE_bnx2x-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_brcmfmac-firmware-usb=(m|y)/# CONFIG_PACKAGE_brcmfmac-firmware-usb is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_carl9170-firmware=(m|y)/# CONFIG_PACKAGE_carl9170-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_e100-firmware=(m|y)/# CONFIG_PACKAGE_e100-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_edgeport-firmware=(m|y)/# CONFIG_PACKAGE_edgeport-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_jboot-tools=(m|y)/# CONFIG_PACKAGE_jboot-tools is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_mt7601u-firmware=(m|y)/# CONFIG_PACKAGE_mt7601u-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_mwifiex-pcie-firmware=(m|y)/# CONFIG_PACKAGE_mwifiex-pcie-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_mwifiex-sdio-firmware=(m|y)/# CONFIG_PACKAGE_mwifiex-sdio-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_mwl8k-firmware=(m|y)/# CONFIG_PACKAGE_mwl8k-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_r8152-firmware=(m|y)/# CONFIG_PACKAGE_r8152-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_r8169-firmware=(m|y)/# CONFIG_PACKAGE_r8169-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rs9113-firmware=(m|y)/# CONFIG_PACKAGE_rs9113-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rt2800-pci-firmware=(m|y)/# CONFIG_PACKAGE_rt2800-pci-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rt2800-usb-firmware=(m|y)/# CONFIG_PACKAGE_rt2800-usb-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rtl8192ce-firmware=(m|y)/# CONFIG_PACKAGE_rtl8192ce-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rtl8192cu-firmware=(m|y)/# CONFIG_PACKAGE_rtl8192cu-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rtl8192de-firmware=(m|y)/# CONFIG_PACKAGE_rtl8192de-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rtl8192se-firmware=(m|y)/# CONFIG_PACKAGE_rtl8192se-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rtl8723de-firmware=(m|y)/# CONFIG_PACKAGE_rtl8723de-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rtl8821ae-firmware=(m|y)/# CONFIG_PACKAGE_rtl8821ae-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rtl8821ce-firmware=(m|y)/# CONFIG_PACKAGE_rtl8821ce-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rtl8822be-firmware=(m|y)/# CONFIG_PACKAGE_rtl8822be-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_rtl8822ce-firmware=(m|y)/# CONFIG_PACKAGE_rtl8822ce-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_wil6210-firmware=(m|y)/# CONFIG_PACKAGE_wil6210-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_wl12xx-firmware=(m|y)/# CONFIG_PACKAGE_wl12xx-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_wl18xx-firmware=(m|y)/# CONFIG_PACKAGE_wl18xx-firmware is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-aoe=(m|y)/# CONFIG_PACKAGE_kmod-aoe is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ata-ahci=(m|y)/# CONFIG_PACKAGE_kmod-ata-ahci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ata-artop=(m|y)/# CONFIG_PACKAGE_kmod-ata-artop is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ata-core=(m|y)/# CONFIG_PACKAGE_kmod-ata-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ata-nvidia-sata=(m|y)/# CONFIG_PACKAGE_kmod-ata-nvidia-sata is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ata-pdc202xx-old=(m|y)/# CONFIG_PACKAGE_kmod-ata-pdc202xx-old is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ata-piix=(m|y)/# CONFIG_PACKAGE_kmod-ata-piix is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ata-sil=(m|y)/# CONFIG_PACKAGE_kmod-ata-sil is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ata-sil24=(m|y)/# CONFIG_PACKAGE_kmod-ata-sil24 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ata-via-sata=(m|y)/# CONFIG_PACKAGE_kmod-ata-via-sata is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-block2mtd=(m|y)/# CONFIG_PACKAGE_kmod-block2mtd is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-dax=(m|y)/# CONFIG_PACKAGE_kmod-dax is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-dm=(m|y)/# CONFIG_PACKAGE_kmod-dm is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-dm-raid=(m|y)/# CONFIG_PACKAGE_kmod-dm-raid is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iosched-bfq=(m|y)/# CONFIG_PACKAGE_kmod-iosched-bfq is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iscsi-initiator=(m|y)/# CONFIG_PACKAGE_kmod-iscsi-initiator is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-loop=(m|y)/# CONFIG_PACKAGE_kmod-loop is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-md-mod=(m|y)/# CONFIG_PACKAGE_kmod-md-mod is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-md-linear=(m|y)/# CONFIG_PACKAGE_kmod-md-linear is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-md-multipath=(m|y)/# CONFIG_PACKAGE_kmod-md-multipath is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-md-raid0=(m|y)/# CONFIG_PACKAGE_kmod-md-raid0 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-md-raid1=(m|y)/# CONFIG_PACKAGE_kmod-md-raid1 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-md-raid10=(m|y)/# CONFIG_PACKAGE_kmod-md-raid10 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-md-raid456=(m|y)/# CONFIG_PACKAGE_kmod-md-raid456 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-nbd=(m|y)/# CONFIG_PACKAGE_kmod-nbd is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-nvme=(m|y)/# CONFIG_PACKAGE_kmod-nvme is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-scsi-cdrom=(m|y)/# CONFIG_PACKAGE_kmod-scsi-cdrom is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-scsi-core=(m|y)/# CONFIG_PACKAGE_kmod-scsi-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-scsi-generic=(m|y)/# CONFIG_PACKAGE_kmod-scsi-generic is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-scsi-tape=(m|y)/# CONFIG_PACKAGE_kmod-scsi-tape is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-can=(m|y)/# CONFIG_PACKAGE_kmod-can is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-bcm=(m|y)/# CONFIG_PACKAGE_kmod-can-bcm is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-c-can=(m|y)/# CONFIG_PACKAGE_kmod-can-c-can is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-c-can-pci=(m|y)/# CONFIG_PACKAGE_kmod-can-c-can-pci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-c-can-platform=(m|y)/# CONFIG_PACKAGE_kmod-can-c-can-platform is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-gw=(m|y)/# CONFIG_PACKAGE_kmod-can-gw is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-mcp251x=(m|y)/# CONFIG_PACKAGE_kmod-can-mcp251x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-raw=(m|y)/# CONFIG_PACKAGE_kmod-can-raw is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-slcan=(m|y)/# CONFIG_PACKAGE_kmod-can-slcan is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-usb-8dev=(m|y)/# CONFIG_PACKAGE_kmod-can-usb-8dev is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-usb-ems=(m|y)/# CONFIG_PACKAGE_kmod-can-usb-ems is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-usb-esd=(m|y)/# CONFIG_PACKAGE_kmod-can-usb-esd is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-usb-kvaser=(m|y)/# CONFIG_PACKAGE_kmod-can-usb-kvaser is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-usb-peak=(m|y)/# CONFIG_PACKAGE_kmod-can-usb-peak is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-can-vcan=(m|y)/# CONFIG_PACKAGE_kmod-can-vcan is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-autofs4=(m|y)/# CONFIG_PACKAGE_kmod-fs-autofs4 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-btrfs=(m|y)/# CONFIG_PACKAGE_kmod-fs-btrfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-cifs=(m|y)/# CONFIG_PACKAGE_kmod-fs-cifs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-configfs=(m|y)/# CONFIG_PACKAGE_kmod-fs-configfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-cramfs=(m|y)/# CONFIG_PACKAGE_kmod-fs-cramfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-exfat=(m|y)/# CONFIG_PACKAGE_kmod-fs-exfat is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-exportfs=(m|y)/# CONFIG_PACKAGE_kmod-fs-exportfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-ext4=(m|y)/# CONFIG_PACKAGE_kmod-fs-ext4 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-f2fs=(m|y)/# CONFIG_PACKAGE_kmod-fs-f2fs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-fscache=(m|y)/# CONFIG_PACKAGE_kmod-fs-fscache is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-hfs=(m|y)/# CONFIG_PACKAGE_kmod-fs-hfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-hfsplus=(m|y)/# CONFIG_PACKAGE_kmod-fs-hfsplus is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-isofs=(m|y)/# CONFIG_PACKAGE_kmod-fs-isofs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-jfs=(m|y)/# CONFIG_PACKAGE_kmod-fs-jfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-ksmbd=(m|y)/# CONFIG_PACKAGE_kmod-fs-ksmbd is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-minix=(m|y)/# CONFIG_PACKAGE_kmod-fs-minix is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-msdos=(m|y)/# CONFIG_PACKAGE_kmod-fs-msdos is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-netfs=(m|y)/# CONFIG_PACKAGE_kmod-fs-netfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-nfs=(m|y)/# CONFIG_PACKAGE_kmod-fs-nfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-nfs-common=(m|y)/# CONFIG_PACKAGE_kmod-fs-nfs-common is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec=(m|y)/# CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-nfs-v3=(m|y)/# CONFIG_PACKAGE_kmod-fs-nfs-v3 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-nfs-v4=(m|y)/# CONFIG_PACKAGE_kmod-fs-nfs-v4 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-nfsd=(m|y)/# CONFIG_PACKAGE_kmod-fs-nfsd is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-ntfs=(m|y)/# CONFIG_PACKAGE_kmod-fs-ntfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-ntfs3=(m|y)/# CONFIG_PACKAGE_kmod-fs-ntfs3 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-reiserfs=(m|y)/# CONFIG_PACKAGE_kmod-fs-reiserfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-smbfs-common=(m|y)/# CONFIG_PACKAGE_kmod-fs-smbfs-common is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-udf=(m|y)/# CONFIG_PACKAGE_kmod-fs-udf is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fs-xfs=(m|y)/# CONFIG_PACKAGE_kmod-fs-xfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-fuse=(m|y)/# CONFIG_PACKAGE_kmod-fuse is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-firewire=(m|y)/# CONFIG_PACKAGE_kmod-firewire is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-firewire-net=(m|y)/# CONFIG_PACKAGE_kmod-firewire-net is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-firewire-ohci=(m|y)/# CONFIG_PACKAGE_kmod-firewire-ohci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-firewire-sbp2=(m|y)/# CONFIG_PACKAGE_kmod-firewire-sbp2 is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-ad7418=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-ad7418 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-adcxx=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-adcxx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-adt7410=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-adt7410 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-adt7475=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-adt7475 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-dme1737=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-dme1737 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-drivetemp=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-drivetemp is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-g762=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-g762 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-gpiofan=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-gpiofan is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-gsc=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-gsc is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-ina209=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-ina209 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-ina2xx=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-ina2xx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-it87=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-it87 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-lm63=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-lm63 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-lm70=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-lm70 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-lm75=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-lm75 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-lm77=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-lm77 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-lm85=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-lm85 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-lm90=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-lm90 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-lm92=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-lm92 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-lm95241=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-lm95241 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-ltc4151=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-ltc4151 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-max6642=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-max6642 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-mcp3021=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-mcp3021 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-nct7802=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-nct7802 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-pwmfan=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-pwmfan is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-sch5627=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-sch5627 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-sht21=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-sht21 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-sht3x=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-sht3x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-tmp102=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-tmp102 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-tmp103=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-tmp103 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-tmp421=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-tmp421 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-tps23861=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-tps23861 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-vid=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-vid is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hwmon-w83793=(m|y)/# CONFIG_PACKAGE_kmod-hwmon-w83793 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-pmbus-core=(m|y)/# CONFIG_PACKAGE_kmod-pmbus-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-pmbus-zl6100=(m|y)/# CONFIG_PACKAGE_kmod-pmbus-zl6100 is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-algo-bit=(m|y)/# CONFIG_PACKAGE_kmod-i2c-algo-bit is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-algo-pca=(m|y)/# CONFIG_PACKAGE_kmod-i2c-algo-pca is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-algo-pcf=(m|y)/# CONFIG_PACKAGE_kmod-i2c-algo-pcf is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-core=(m|y)/# CONFIG_PACKAGE_kmod-i2c-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-designware-core=(m|y)/# CONFIG_PACKAGE_kmod-i2c-designware-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-designware-pci=(m|y)/# CONFIG_PACKAGE_kmod-i2c-designware-pci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-gpio=(m|y)/# CONFIG_PACKAGE_kmod-i2c-gpio is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-mux=(m|y)/# CONFIG_PACKAGE_kmod-i2c-mux is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-mux-gpio=(m|y)/# CONFIG_PACKAGE_kmod-i2c-mux-gpio is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-mux-pca9541=(m|y)/# CONFIG_PACKAGE_kmod-i2c-mux-pca9541 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-mux-pca954x=(m|y)/# CONFIG_PACKAGE_kmod-i2c-mux-pca954x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-pxa=(m|y)/# CONFIG_PACKAGE_kmod-i2c-pxa is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-smbus=(m|y)/# CONFIG_PACKAGE_kmod-i2c-smbus is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i2c-tiny-usb=(m|y)/# CONFIG_PACKAGE_kmod-i2c-tiny-usb is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-ad799x=(m|y)/# CONFIG_PACKAGE_kmod-iio-ad799x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-ads1015=(m|y)/# CONFIG_PACKAGE_kmod-iio-ads1015 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-am2315=(m|y)/# CONFIG_PACKAGE_kmod-iio-am2315 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-bh1750=(m|y)/# CONFIG_PACKAGE_kmod-iio-bh1750 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-bme680=(m|y)/# CONFIG_PACKAGE_kmod-iio-bme680 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-bme680-i2c=(m|y)/# CONFIG_PACKAGE_kmod-iio-bme680-i2c is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-bme680-spi=(m|y)/# CONFIG_PACKAGE_kmod-iio-bme680-spi is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-bmp280=(m|y)/# CONFIG_PACKAGE_kmod-iio-bmp280 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-bmp280-i2c=(m|y)/# CONFIG_PACKAGE_kmod-iio-bmp280-i2c is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-bmp280-spi=(m|y)/# CONFIG_PACKAGE_kmod-iio-bmp280-spi is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-ccs811=(m|y)/# CONFIG_PACKAGE_kmod-iio-ccs811 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-core=(m|y)/# CONFIG_PACKAGE_kmod-iio-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-dht11=(m|y)/# CONFIG_PACKAGE_kmod-iio-dht11 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-fxas21002c=(m|y)/# CONFIG_PACKAGE_kmod-iio-fxas21002c is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-fxas21002c-i2c=(m|y)/# CONFIG_PACKAGE_kmod-iio-fxas21002c-i2c is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-fxas21002c-spi=(m|y)/# CONFIG_PACKAGE_kmod-iio-fxas21002c-spi is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-fxos8700=(m|y)/# CONFIG_PACKAGE_kmod-iio-fxos8700 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-fxos8700-i2c=(m|y)/# CONFIG_PACKAGE_kmod-iio-fxos8700-i2c is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-fxos8700-spi=(m|y)/# CONFIG_PACKAGE_kmod-iio-fxos8700-spi is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-hmc5843=(m|y)/# CONFIG_PACKAGE_kmod-iio-hmc5843 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-htu21=(m|y)/# CONFIG_PACKAGE_kmod-iio-htu21 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-kfifo-buf=(m|y)/# CONFIG_PACKAGE_kmod-iio-kfifo-buf is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-lsm6dsx=(m|y)/# CONFIG_PACKAGE_kmod-iio-lsm6dsx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-lsm6dsx-i2c=(m|y)/# CONFIG_PACKAGE_kmod-iio-lsm6dsx-i2c is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-lsm6dsx-spi=(m|y)/# CONFIG_PACKAGE_kmod-iio-lsm6dsx-spi is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-si7020=(m|y)/# CONFIG_PACKAGE_kmod-iio-si7020 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-sps30=(m|y)/# CONFIG_PACKAGE_kmod-iio-sps30 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-st_accel=(m|y)/# CONFIG_PACKAGE_kmod-iio-st_accel is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-st_accel-i2c=(m|y)/# CONFIG_PACKAGE_kmod-iio-st_accel-i2c is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-st_accel-spi=(m|y)/# CONFIG_PACKAGE_kmod-iio-st_accel-spi is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iio-tsl4531=(m|y)/# CONFIG_PACKAGE_kmod-iio-tsl4531 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-industrialio-triggered-buffer=(m|y)/# CONFIG_PACKAGE_kmod-industrialio-triggered-buffer is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-hid=(m|y)/# CONFIG_PACKAGE_kmod-hid is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hid-generic=(m|y)/# CONFIG_PACKAGE_kmod-hid-generic is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-input-core=(m|y)/# CONFIG_PACKAGE_kmod-input-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-input-evdev=(m|y)/# CONFIG_PACKAGE_kmod-input-evdev is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-input-gpio-encoder=(m|y)/# CONFIG_PACKAGE_kmod-input-gpio-encoder is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-input-gpio-keys=(m|y)/# CONFIG_PACKAGE_kmod-input-gpio-keys is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-input-gpio-keys-polled=(m|y)/# CONFIG_PACKAGE_kmod-input-gpio-keys-polled is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-input-joydev=(m|y)/# CONFIG_PACKAGE_kmod-input-joydev is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-input-matrixkmap=(m|y)/# CONFIG_PACKAGE_kmod-input-matrixkmap is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-input-touchscreen-ads7846=(m|y)/# CONFIG_PACKAGE_kmod-input-touchscreen-ads7846 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-input-touchscreen-edt-ft5x06=(m|y)/# CONFIG_PACKAGE_kmod-input-touchscreen-edt-ft5x06 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-input-uinput=(m|y)/# CONFIG_PACKAGE_kmod-input-uinput is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-input-leds=(m|y)/# CONFIG_PACKAGE_kmod-input-leds is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-leds-gpio=(m|y)/# CONFIG_PACKAGE_kmod-leds-gpio is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-leds-pca955x=(m|y)/# CONFIG_PACKAGE_kmod-leds-pca955x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-leds-pca963x=(m|y)/# CONFIG_PACKAGE_kmod-leds-pca963x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-leds-tlc591xx=(m|y)/# CONFIG_PACKAGE_kmod-leds-tlc591xx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-leds-ubnt-ledbar=(m|y)/# CONFIG_PACKAGE_kmod-leds-ubnt-ledbar is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-leds-uleds=(m|y)/# CONFIG_PACKAGE_kmod-leds-uleds is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ledtrig-activity=(m|y)/# CONFIG_PACKAGE_kmod-ledtrig-activity is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ledtrig-audio=(m|y)/# CONFIG_PACKAGE_kmod-ledtrig-audio is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ledtrig-gpio=(m|y)/# CONFIG_PACKAGE_kmod-ledtrig-gpio is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ledtrig-oneshot=(m|y)/# CONFIG_PACKAGE_kmod-ledtrig-oneshot is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ledtrig-pattern=(m|y)/# CONFIG_PACKAGE_kmod-ledtrig-pattern is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ledtrig-transient=(m|y)/# CONFIG_PACKAGE_kmod-ledtrig-transient is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ledtrig-tty=(m|y)/# CONFIG_PACKAGE_kmod-ledtrig-tty is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-3c59x=(m|y)/# CONFIG_PACKAGE_kmod-3c59x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-8139cp=(m|y)/# CONFIG_PACKAGE_kmod-8139cp is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-8139too=(m|y)/# CONFIG_PACKAGE_kmod-8139too is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-alx=(m|y)/# CONFIG_PACKAGE_kmod-alx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-atl1=(m|y)/# CONFIG_PACKAGE_kmod-atl1 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-atl1c=(m|y)/# CONFIG_PACKAGE_kmod-atl1c is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-atl1e=(m|y)/# CONFIG_PACKAGE_kmod-atl1e is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-atl2=(m|y)/# CONFIG_PACKAGE_kmod-atl2 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-atlantic=(m|y)/# CONFIG_PACKAGE_kmod-atlantic is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-b44=(m|y)/# CONFIG_PACKAGE_kmod-b44 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-be2net=(m|y)/# CONFIG_PACKAGE_kmod-be2net is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-bnx2=(m|y)/# CONFIG_PACKAGE_kmod-bnx2 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-bnx2x=(m|y)/# CONFIG_PACKAGE_kmod-bnx2x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-bnxt-en=(m|y)/# CONFIG_PACKAGE_kmod-bnxt-en is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-dm9000=(m|y)/# CONFIG_PACKAGE_kmod-dm9000 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-e100=(m|y)/# CONFIG_PACKAGE_kmod-e100 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-e1000=(m|y)/# CONFIG_PACKAGE_kmod-e1000 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-et131x=(m|y)/# CONFIG_PACKAGE_kmod-et131x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ethoc=(m|y)/# CONFIG_PACKAGE_kmod-ethoc is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-forcedeth=(m|y)/# CONFIG_PACKAGE_kmod-forcedeth is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hfcmulti=(m|y)/# CONFIG_PACKAGE_kmod-hfcmulti is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-hfcpci=(m|y)/# CONFIG_PACKAGE_kmod-hfcpci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-i40e=(m|y)/# CONFIG_PACKAGE_kmod-i40e is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-iavf=(m|y)/# CONFIG_PACKAGE_kmod-iavf is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ice=(m|y)/# CONFIG_PACKAGE_kmod-ice is not set/' .config
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/
sed -i -E 's/CONFIG_PACKAGE_kmod-ifb=(m|y)/# CONFIG_PACKAGE_kmod-ifb is not set/' .config
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/
# sed -i -E 's/CONFIG_PACKAGE_kmod-igb=(m|y)/# CONFIG_PACKAGE_kmod-igb is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-igc=(m|y)/# CONFIG_PACKAGE_kmod-igc is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ipvlan=(m|y)/# CONFIG_PACKAGE_kmod-ipvlan is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ixgbe=(m|y)/# CONFIG_PACKAGE_kmod-ixgbe is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ixgbevf=(m|y)/# CONFIG_PACKAGE_kmod-ixgbevf is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-lan743x=(m|y)/# CONFIG_PACKAGE_kmod-lan743x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-mdio-devres=(m|y)/# CONFIG_PACKAGE_kmod-mdio-devres is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-mdio-gpio=(m|y)/# CONFIG_PACKAGE_kmod-mdio-gpio is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-mhi-net=(m|y)/# CONFIG_PACKAGE_kmod-mhi-net is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-mhi-wwan-ctrl=(m|y)/# CONFIG_PACKAGE_kmod-mhi-wwan-ctrl is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-mhi-wwan-mbim=(m|y)/# CONFIG_PACKAGE_kmod-mhi-wwan-mbim is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-mii=(m|y)/# CONFIG_PACKAGE_kmod-mii is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-mlx4-core=(m|y)/# CONFIG_PACKAGE_kmod-mlx4-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-mlx5-core=(m|y)/# CONFIG_PACKAGE_kmod-mlx5-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-mtk-t7xx=(m|y)/# CONFIG_PACKAGE_kmod-mtk-t7xx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-natsemi=(m|y)/# CONFIG_PACKAGE_kmod-natsemi is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ne2k-pci=(m|y)/# CONFIG_PACKAGE_kmod-ne2k-pci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-net-selftests=(m|y)/# CONFIG_PACKAGE_kmod-net-selftests is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-pcnet32=(m|y)/# CONFIG_PACKAGE_kmod-pcnet32 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-phy-aquantia=(m|y)/# CONFIG_PACKAGE_kmod-phy-aquantia is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-phy-ax88796b=(m|y)/# CONFIG_PACKAGE_kmod-phy-ax88796b is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-phy-bcm84881=(m|y)/# CONFIG_PACKAGE_kmod-phy-bcm84881 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-phy-broadcom=(m|y)/# CONFIG_PACKAGE_kmod-phy-broadcom is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-phy-marvell=(m|y)/# CONFIG_PACKAGE_kmod-phy-marvell is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-phy-marvell-10g=(m|y)/# CONFIG_PACKAGE_kmod-phy-marvell-10g is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-phy-microchip=(m|y)/# CONFIG_PACKAGE_kmod-phy-microchip is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-phy-realtek=(m|y)/# CONFIG_PACKAGE_kmod-phy-realtek is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-phy-smsc=(m|y)/# CONFIG_PACKAGE_kmod-phy-smsc is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-phylib-broadcom=(m|y)/# CONFIG_PACKAGE_kmod-phylib-broadcom is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-qede=(m|y)/# CONFIG_PACKAGE_kmod-qede is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-qlcnic=(m|y)/# CONFIG_PACKAGE_kmod-qlcnic is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-r6040=(m|y)/# CONFIG_PACKAGE_kmod-r6040 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-r8101=(m|y)/# CONFIG_PACKAGE_kmod-r8101 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-r8125=(m|y)/# CONFIG_PACKAGE_kmod-r8125 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-r8168=(m|y)/# CONFIG_PACKAGE_kmod-r8168 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-r8169=(m|y)/# CONFIG_PACKAGE_kmod-r8169 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sis190=(m|y)/# CONFIG_PACKAGE_kmod-sis190 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sis900=(m|y)/# CONFIG_PACKAGE_kmod-sis900 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-skge=(m|y)/# CONFIG_PACKAGE_kmod-skge is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sky2=(m|y)/# CONFIG_PACKAGE_kmod-sky2 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-solos-pci=(m|y)/# CONFIG_PACKAGE_kmod-solos-pci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-spi-ks8995=(m|y)/# CONFIG_PACKAGE_kmod-spi-ks8995 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-switch-ar8xxx=(m|y)/# CONFIG_PACKAGE_kmod-switch-ar8xxx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-switch-bcm53xx=(m|y)/# CONFIG_PACKAGE_kmod-switch-bcm53xx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-switch-bcm53xx-mdio=(m|y)/# CONFIG_PACKAGE_kmod-switch-bcm53xx-mdio is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-switch-ip17xx=(m|y)/# CONFIG_PACKAGE_kmod-switch-ip17xx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-switch-rtl8306=(m|y)/# CONFIG_PACKAGE_kmod-switch-rtl8306 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-switch-rtl8366-smi=(m|y)/# CONFIG_PACKAGE_kmod-switch-rtl8366-smi is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-switch-rtl8366rb=(m|y)/# CONFIG_PACKAGE_kmod-switch-rtl8366rb is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-switch-rtl8366s=(m|y)/# CONFIG_PACKAGE_kmod-switch-rtl8366s is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-switch-rtl8367=(m|y)/# CONFIG_PACKAGE_kmod-switch-rtl8367 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-switch-rtl8367b=(m|y)/# CONFIG_PACKAGE_kmod-switch-rtl8367b is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-tg3=(m|y)/# CONFIG_PACKAGE_kmod-tg3 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-tulip=(m|y)/# CONFIG_PACKAGE_kmod-tulip is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-via-rhine=(m|y)/# CONFIG_PACKAGE_kmod-via-rhine is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-via-velocity=(m|y)/# CONFIG_PACKAGE_kmod-via-velocity is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-vmxnet3=(m|y)/# CONFIG_PACKAGE_kmod-vmxnet3 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-wwan=(m|y)/# CONFIG_PACKAGE_kmod-wwan is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-openvswitch=(m|y)/# CONFIG_PACKAGE_kmod-openvswitch is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-openvswitch-geneve=(m|y)/# CONFIG_PACKAGE_kmod-openvswitch-geneve is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-openvswitch-geneve-intree=(m|y)/# CONFIG_PACKAGE_kmod-openvswitch-geneve-intree is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-openvswitch-gre=(m|y)/# CONFIG_PACKAGE_kmod-openvswitch-gre is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-openvswitch-gre-intree=(m|y)/# CONFIG_PACKAGE_kmod-openvswitch-gre-intree is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-openvswitch-intree=(m|y)/# CONFIG_PACKAGE_kmod-openvswitch-intree is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-openvswitch-lisp-intree=(m|y)/# CONFIG_PACKAGE_kmod-openvswitch-lisp-intree is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-openvswitch-stt-intree=(m|y)/# CONFIG_PACKAGE_kmod-openvswitch-stt-intree is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-openvswitch-vxlan=(m|y)/# CONFIG_PACKAGE_kmod-openvswitch-vxlan is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-openvswitch-vxlan-intree=(m|y)/# CONFIG_PACKAGE_kmod-openvswitch-vxlan-intree is not set/' .config

sed -i -E 's/CONFIG_PACKAGE_kmod-6lowpan=(m|y)/# CONFIG_PACKAGE_kmod-6lowpan is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-ath3k=(m|y)/# CONFIG_PACKAGE_kmod-ath3k is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-bcma=(m|y)/# CONFIG_PACKAGE_kmod-bcma is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-bluetooth=(m|y)/# CONFIG_PACKAGE_kmod-bluetooth is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-bluetooth-6lowpan=(m|y)/# CONFIG_PACKAGE_kmod-bluetooth-6lowpan is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-btmrvl=(m|y)/# CONFIG_PACKAGE_kmod-btmrvl is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-btsdio=(m|y)/# CONFIG_PACKAGE_kmod-btsdio is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-button-hotplug=(m|y)/# CONFIG_PACKAGE_kmod-button-hotplug is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-dma-buf=(m|y)/# CONFIG_PACKAGE_kmod-dma-buf is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-dma-ralink=(m|y)/# CONFIG_PACKAGE_kmod-dma-ralink is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-echo=(m|y)/# CONFIG_PACKAGE_kmod-echo is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-eeprom-93cx6=(m|y)/# CONFIG_PACKAGE_kmod-eeprom-93cx6 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-eeprom-at24=(m|y)/# CONFIG_PACKAGE_kmod-eeprom-at24 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-eeprom-at25=(m|y)/# CONFIG_PACKAGE_kmod-eeprom-at25 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-google-firmware=(m|y)/# CONFIG_PACKAGE_kmod-google-firmware is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-gpio-beeper=(m|y)/# CONFIG_PACKAGE_kmod-gpio-beeper is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-gpio-button-hotplug=(m|y)/# CONFIG_PACKAGE_kmod-gpio-button-hotplug is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-gpio-nxp-74hc164=(m|y)/# CONFIG_PACKAGE_kmod-gpio-nxp-74hc164 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-gpio-pca953x=(m|y)/# CONFIG_PACKAGE_kmod-gpio-pca953x is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-gpio-pcf857x=(m|y)/# CONFIG_PACKAGE_kmod-gpio-pcf857x is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-hsdma-mtk=(m|y)/# CONFIG_PACKAGE_kmod-hsdma-mtk is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-i6300esb-wdt=(m|y)/# CONFIG_PACKAGE_kmod-i6300esb-wdt is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-ikconfig=(m|y)/# CONFIG_PACKAGE_kmod-ikconfig is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-imx2-wdt=(m|y)/# CONFIG_PACKAGE_kmod-imx2-wdt is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-imx7-ulp-wdt=(m|y)/# CONFIG_PACKAGE_kmod-imx7-ulp-wdt is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-keys-encrypted=(m|y)/# CONFIG_PACKAGE_kmod-keys-encrypted is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-keys-trusted=(m|y)/# CONFIG_PACKAGE_kmod-keys-trusted is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-lkdtm=(m|y)/# CONFIG_PACKAGE_kmod-lkdtm is not set/' .config
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/
sed -i -E 's/CONFIG_PACKAGE_kmod-mhi-bus=(m|y)/# CONFIG_PACKAGE_kmod-mhi-bus is not set/' .config
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/
sed -i -E 's/CONFIG_PACKAGE_kmod-mhi-pci-generic=(m|y)/# CONFIG_PACKAGE_kmod-mhi-pci-generic is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-parport-pc=(m|y)/# CONFIG_PACKAGE_kmod-parport-pc is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-pinctrl-mcp23s08=(m|y)/# CONFIG_PACKAGE_kmod-pinctrl-mcp23s08 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-pinctrl-mcp23s08-i2c=(m|y)/# CONFIG_PACKAGE_kmod-pinctrl-mcp23s08-i2c is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-pinctrl-mcp23s08-spi=(m|y)/# CONFIG_PACKAGE_kmod-pinctrl-mcp23s08-spi is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-ppdev=(m|y)/# CONFIG_PACKAGE_kmod-ppdev is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-pps=(m|y)/# CONFIG_PACKAGE_kmod-pps is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-pps-gpio=(m|y)/# CONFIG_PACKAGE_kmod-pps-gpio is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-pps-ldisc=(m|y)/# CONFIG_PACKAGE_kmod-pps-ldisc is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-ptp=(m|y)/# CONFIG_PACKAGE_kmod-ptp is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-ramoops=(m|y)/# CONFIG_PACKAGE_kmod-ramoops is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-reed-solomon=(m|y)/# CONFIG_PACKAGE_kmod-reed-solomon is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-regmap-core=(m|y)/# CONFIG_PACKAGE_kmod-regmap-core is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-regmap-i2c=(m|y)/# CONFIG_PACKAGE_kmod-regmap-i2c is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-regmap-spi=(m|y)/# CONFIG_PACKAGE_kmod-regmap-spi is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-rtc-ds1307=(m|y)/# CONFIG_PACKAGE_kmod-rtc-ds1307 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-rtc-ds1374=(m|y)/# CONFIG_PACKAGE_kmod-rtc-ds1374 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-rtc-ds1672=(m|y)/# CONFIG_PACKAGE_kmod-rtc-ds1672 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-rtc-em3027=(m|y)/# CONFIG_PACKAGE_kmod-rtc-em3027 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-rtc-isl1208=(m|y)/# CONFIG_PACKAGE_kmod-rtc-isl1208 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-rtc-pcf2123=(m|y)/# CONFIG_PACKAGE_kmod-rtc-pcf2123 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-rtc-pcf2127=(m|y)/# CONFIG_PACKAGE_kmod-rtc-pcf2127 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-rtc-pcf8563=(m|y)/# CONFIG_PACKAGE_kmod-rtc-pcf8563 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-rtc-rs5c372a=(m|y)/# CONFIG_PACKAGE_kmod-rtc-rs5c372a is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-rtc-rx8025=(m|y)/# CONFIG_PACKAGE_kmod-rtc-rx8025 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-rtc-s35390a=(m|y)/# CONFIG_PACKAGE_kmod-rtc-s35390a is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-sdhci=(m|y)/# CONFIG_PACKAGE_kmod-sdhci is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-sdhci-mt7620=(m|y)/# CONFIG_PACKAGE_kmod-sdhci-mt7620 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-serial-8250=(m|y)/# CONFIG_PACKAGE_kmod-serial-8250 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-serial-8250-exar=(m|y)/# CONFIG_PACKAGE_kmod-serial-8250-exar is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-ssb=(m|y)/# CONFIG_PACKAGE_kmod-ssb is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-tpm=(m|y)/# CONFIG_PACKAGE_kmod-tpm is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-tpm-i2c-atmel=(m|y)/# CONFIG_PACKAGE_kmod-tpm-i2c-atmel is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-tpm-i2c-infineon=(m|y)/# CONFIG_PACKAGE_kmod-tpm-i2c-infineon is not set/' .config

sed -i -E 's/CONFIG_PACKAGE_kmod-mmc-spi=(m|y)/# CONFIG_PACKAGE_kmod-mmc-spi is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-spi-bitbang=(m|y)/# CONFIG_PACKAGE_kmod-spi-bitbang is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-spi-dev=(m|y)/# CONFIG_PACKAGE_kmod-spi-dev is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-spi-gpio=(m|y)/# CONFIG_PACKAGE_kmod-spi-gpio is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-core=(m|y)/# CONFIG_PACKAGE_kmod-sound-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-ac97=(m|y)/# CONFIG_PACKAGE_kmod-ac97 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-dummy=(m|y)/# CONFIG_PACKAGE_kmod-sound-dummy is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-ens1371=(m|y)/# CONFIG_PACKAGE_kmod-sound-ens1371 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-core=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-codec-analog=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-codec-analog is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-codec-ca0110=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-codec-ca0110 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-codec-ca0132=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-codec-ca0132 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-codec-cirrus=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-codec-cirrus is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-codec-cmedia=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-codec-cmedia is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-codec-conexant=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-codec-conexant is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-codec-hdmi=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-codec-hdmi is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-codec-idt=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-codec-idt is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-codec-realtek=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-codec-realtek is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-codec-si3054=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-codec-si3054 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-hda-codec-via=(m|y)/# CONFIG_PACKAGE_kmod-sound-hda-codec-via is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-i8x0=(m|y)/# CONFIG_PACKAGE_kmod-sound-i8x0 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-mpu401=(m|y)/# CONFIG_PACKAGE_kmod-sound-mpu401 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-mt7620=(m|y)/# CONFIG_PACKAGE_kmod-sound-mt7620 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-seq=(m|y)/# CONFIG_PACKAGE_kmod-sound-seq is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-soc-ac97=(m|y)/# CONFIG_PACKAGE_kmod-sound-soc-ac97 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-soc-core=(m|y)/# CONFIG_PACKAGE_kmod-sound-soc-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-soc-spdif=(m|y)/# CONFIG_PACKAGE_kmod-sound-soc-spdif is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-sound-via82xx=(m|y)/# CONFIG_PACKAGE_kmod-sound-via82xx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-audio=(m|y)/# CONFIG_PACKAGE_kmod-usb-audio is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-chaoskey=(m|y)/# CONFIG_PACKAGE_kmod-chaoskey is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-acm=(m|y)/# CONFIG_PACKAGE_kmod-usb-acm is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-atm=(m|y)/# CONFIG_PACKAGE_kmod-usb-atm is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-atm-cxacru=(m|y)/# CONFIG_PACKAGE_kmod-usb-atm-cxacru is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-atm-speedtouch=(m|y)/# CONFIG_PACKAGE_kmod-usb-atm-speedtouch is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-atm-ueagle=(m|y)/# CONFIG_PACKAGE_kmod-usb-atm-ueagle is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-cm109=(m|y)/# CONFIG_PACKAGE_kmod-usb-cm109 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-core=(m|y)/# CONFIG_PACKAGE_kmod-usb-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-dwc2=(m|y)/# CONFIG_PACKAGE_kmod-usb-dwc2 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-dwc2-pci=(m|y)/# CONFIG_PACKAGE_kmod-usb-dwc2-pci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-dwc3=(m|y)/# CONFIG_PACKAGE_kmod-usb-dwc3 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-ehci=(m|y)/# CONFIG_PACKAGE_kmod-usb-ehci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-hid=(m|y)/# CONFIG_PACKAGE_kmod-usb-hid is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-hid-cp2112=(m|y)/# CONFIG_PACKAGE_kmod-usb-hid-cp2112 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-hid-mcp2221=(m|y)/# CONFIG_PACKAGE_kmod-usb-hid-mcp2221 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-ledtrig-usbport=(m|y)/# CONFIG_PACKAGE_kmod-usb-ledtrig-usbport is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net=(m|y)/# CONFIG_PACKAGE_kmod-usb-net is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-aqc111=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-aqc111 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-asix=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-asix is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-asix-ax88179=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-asix-ax88179 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-cdc-eem=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-cdc-eem is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-cdc-ether=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-cdc-ether is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-cdc-mbim=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-cdc-mbim is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-cdc-ncm=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-cdc-ncm is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-cdc-subset=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-cdc-subset is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-dm9601-ether=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-dm9601-ether is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-hso=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-hso is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-huawei-cdc-ncm=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-huawei-cdc-ncm is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-ipheth=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-ipheth is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-kalmia=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-kalmia is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-kaweth=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-kaweth is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-lan78xx=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-lan78xx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-mcs7830=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-mcs7830 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-pegasus=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-pegasus is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-pl=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-pl is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-qmi-wwan is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-qmi-wwan-fibocom=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-qmi-wwan-fibocom is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-qmi-wwan-quectel=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-qmi-wwan-quectel is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-rndis=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-rndis is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-rtl8150=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-rtl8150 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-rtl8152=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-rtl8152 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-rtl8152-vendor=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-rtl8152-vendor is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-sierrawireless=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-sierrawireless is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-smsc75xx=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-smsc75xx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-smsc95xx=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-smsc95xx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-net-sr9700=(m|y)/# CONFIG_PACKAGE_kmod-usb-net-sr9700 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-ohci=(m|y)/# CONFIG_PACKAGE_kmod-usb-ohci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-ohci-pci=(m|y)/# CONFIG_PACKAGE_kmod-usb-ohci-pci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-phy-nop=(m|y)/# CONFIG_PACKAGE_kmod-usb-phy-nop is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-printer=(m|y)/# CONFIG_PACKAGE_kmod-usb-printer is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-roles=(m|y)/# CONFIG_PACKAGE_kmod-usb-roles is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-ark3116=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-ark3116 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-belkin=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-belkin is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-ch341=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-ch341 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-cp210x=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-cp210x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-cypress-m8=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-cypress-m8 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-dmx_usb_module=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-dmx_usb_module is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-edgeport=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-edgeport is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-ftdi=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-ftdi is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-garmin=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-garmin is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-ipw=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-ipw is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-keyspan=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-keyspan is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-mct=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-mct is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-mos7720=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-mos7720 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-mos7840=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-mos7840 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-option=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-option is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-oti6858=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-oti6858 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-pl2303=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-pl2303 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-qualcomm=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-qualcomm is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-sierrawireless=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-sierrawireless is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-simple=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-simple is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-ti-usb=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-ti-usb is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-visor=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-visor is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-wwan=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-wwan is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-serial-xr_usb_serial_common=(m|y)/# CONFIG_PACKAGE_kmod-usb-serial-xr_usb_serial_common is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-storage=(m|y)/# CONFIG_PACKAGE_kmod-usb-storage is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-storage-extras=(m|y)/# CONFIG_PACKAGE_kmod-usb-storage-extras is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-storage-uas=(m|y)/# CONFIG_PACKAGE_kmod-usb-storage-uas is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-test=(m|y)/# CONFIG_PACKAGE_kmod-usb-test is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-uhci=(m|y)/# CONFIG_PACKAGE_kmod-usb-uhci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-wdm=(m|y)/# CONFIG_PACKAGE_kmod-usb-wdm is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-xhci-hcd=(m|y)/# CONFIG_PACKAGE_kmod-usb-xhci-hcd is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-xhci-mtk=(m|y)/# CONFIG_PACKAGE_kmod-usb-xhci-mtk is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb-yealink=(m|y)/# CONFIG_PACKAGE_kmod-usb-yealink is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb2=(m|y)/# CONFIG_PACKAGE_kmod-usb2 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb2-pci=(m|y)/# CONFIG_PACKAGE_kmod-usb2-pci is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usb3=(m|y)/# CONFIG_PACKAGE_kmod-usb3 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usbip=(m|y)/# CONFIG_PACKAGE_kmod-usbip is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usbip-client=(m|y)/# CONFIG_PACKAGE_kmod-usbip-client is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usbip-server=(m|y)/# CONFIG_PACKAGE_kmod-usbip-server is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-usbmon=(m|y)/# CONFIG_PACKAGE_kmod-usbmon is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_kmod-multimedia-input=(m|y)/# CONFIG_PACKAGE_kmod-multimedia-input is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-core=(m|y)/# CONFIG_PACKAGE_kmod-video-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-v4l2loopback=(m|y)/# CONFIG_PACKAGE_kmod-v4l2loopback is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-cpia2=(m|y)/# CONFIG_PACKAGE_kmod-video-cpia2 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-core=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-core is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-conex=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-conex is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-etoms=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-etoms is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-finepix=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-finepix is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-gl860=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-gl860 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-jeilinj=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-jeilinj is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-konica=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-konica is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-m5602=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-m5602 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-mars=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-mars is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-mr97310a=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-mr97310a is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-ov519=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-ov519 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-ov534=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-ov534 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-ov534-9=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-ov534-9 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-pac207=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-pac207 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-pac7311=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-pac7311 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-se401=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-se401 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-sn9c20x=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-sn9c20x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-sonixb=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-sonixb is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-sonixj=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-sonixj is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-spca500=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-spca500 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-spca501=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-spca501 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-spca505=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-spca505 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-spca506=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-spca506 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-spca508=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-spca508 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-spca561=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-spca561 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-sq905=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-sq905 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-sq905c=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-sq905c is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-sq930x=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-sq930x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-stk014=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-stk014 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-stv06xx=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-stv06xx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-sunplus=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-sunplus is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-t613=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-t613 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-tv8532=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-tv8532 is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-vc032x=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-vc032x is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-gspca-zc3xx=(m|y)/# CONFIG_PACKAGE_kmod-video-gspca-zc3xx is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-pwc=(m|y)/# CONFIG_PACKAGE_kmod-video-pwc is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-uvc=(m|y)/# CONFIG_PACKAGE_kmod-video-uvc is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_kmod-video-videobuf2=(m|y)/# CONFIG_PACKAGE_kmod-video-videobuf2 is not set/' .config

sed -i -E 's/CONFIG_PACKAGE_kmod-vhost=(m|y)/# CONFIG_PACKAGE_kmod-vhost is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-vhost-net=(m|y)/# CONFIG_PACKAGE_kmod-vhost-net is not set/' .config

sed -i -E 's/CONFIG_PACKAGE_kmod-w1=(m|y)/# CONFIG_PACKAGE_kmod-w1 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-w1-master-ds2482=(m|y)/# CONFIG_PACKAGE_kmod-w1-master-ds2482 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-w1-master-ds2490=(m|y)/# CONFIG_PACKAGE_kmod-w1-master-ds2490 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-w1-master-gpio=(m|y)/# CONFIG_PACKAGE_kmod-w1-master-gpio is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-w1-slave-ds2413=(m|y)/# CONFIG_PACKAGE_kmod-w1-slave-ds2413 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-w1-slave-ds2431=(m|y)/# CONFIG_PACKAGE_kmod-w1-slave-ds2431 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-w1-slave-ds2433=(m|y)/# CONFIG_PACKAGE_kmod-w1-slave-ds2433 is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-w1-slave-smem=(m|y)/# CONFIG_PACKAGE_kmod-w1-slave-smem is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_kmod-w1-slave-therm=(m|y)/# CONFIG_PACKAGE_kmod-w1-slave-therm is not set/' .config


#sed -i 's/CONFIG_WOLFSSL_HAS_AES_CCM=(m|y)/# CONFIG_WOLFSSL_HAS_AES_CCM is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_HAS_CHACHA_POLY=(m|y)/# CONFIG_WOLFSSL_HAS_CHACHA_POLY is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_HAS_DH=(m|y)/# CONFIG_WOLFSSL_HAS_DH is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_HAS_ARC4=(m|y)/# CONFIG_WOLFSSL_HAS_ARC4 is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_HAS_CERTGEN=(m|y)/# CONFIG_WOLFSSL_HAS_CERTGEN is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_HAS_TLSV10=(m|y)/# CONFIG_WOLFSSL_HAS_TLSV10 is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_HAS_TLSV13=(m|y)/# CONFIG_WOLFSSL_HAS_TLSV13 is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_HAS_SESSION_TICKET=(m|y)/# CONFIG_WOLFSSL_HAS_SESSION_TICKET is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_HAS_OCSP=(m|y)/# CONFIG_WOLFSSL_HAS_OCSP is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_HAS_WPAS=(m|y)/# CONFIG_WOLFSSL_HAS_WPAS is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_HAS_ECC25519=(m|y)/# CONFIG_WOLFSSL_HAS_ECC25519 is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_HAS_OPENVPN=(m|y)/# CONFIG_WOLFSSL_HAS_OPENVPN is not set/' .config
#sed -i 's/CONFIG_WOLFSSL_ALT_NAMES=(m|y)/# CONFIG_WOLFSSL_ALT_NAMES is not set/' .config

# sed -i -E 's/CONFIG_PACKAGE_luci=(m|y)/# CONFIG_PACKAGE_luci is not set/' .config
sed -i -E 's/CONFIG_LUCI_JSMIN=(m|y)/# CONFIG_LUCI_JSMIN is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_luci-light=(m|y)/# CONFIG_PACKAGE_luci-light is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs=(m|y)/# CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk=(m|y)/# CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_luci-app-firewall=(m|y)/# CONFIG_PACKAGE_luci-app-firewall is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_luci-app-opkg=(m|y)/# CONFIG_PACKAGE_luci-app-opkg is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client=(m|y)/# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client=(m|y)/# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs=(m|y)/# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus=(m|y)/# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui=(m|y)/# CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng=(m|y)/# CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_default-settings=(m|y)/# CONFIG_PACKAGE_default-settings is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_default-settings-chn=(m|y)/# CONFIG_PACKAGE_default-settings-chn is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=(m|y)/# CONFIG_PACKAGE_luci-i18n-firewall-zh-cn is not set/' .config
# sed -i -E 's/CONFIG_PACKAGE_luci-i18n-opkg-zh-cn=(m|y)/# CONFIG_PACKAGE_luci-i18n-opkg-zh-cn is not set/' .config
sed -i -E 's/CONFIG_PCAP_DNSPROXY_LIBPCAP=(m|y)/# CONFIG_PCAP_DNSPROXY_LIBPCAP is not set/' .config
sed -i -E 's/CONFIG_PCAP_DNSPROXY_LIBSODIUM=(m|y)/# CONFIG_PCAP_DNSPROXY_LIBSODIUM is not set/' .config
sed -i -E 's/CONFIG_PCAP_DNSPROXY_TLS=(m|y)/# CONFIG_PCAP_DNSPROXY_TLS is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_ip-tiny=(m|y)/# CONFIG_PACKAGE_tc-tiny is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_tc-tiny=(m|y)/# CONFIG_PACKAGE_tc-tiny is not set/' .config
sed -i -E 's/CONFIG_PACKAGE_ifstat=(m|y)/# CONFIG_PACKAGE_ifstat is not set/' .config

sed -i -E 's/CONFIG_LINUX_5_15=(m|y)/CONFIG_LINUX_6_6=y/' .config


# Enable 802.11k/v/r
# sed -i 's/RRMEnable=0/RRMEnable=1/g' package/kernel/mt-drivers/mt_wifi/files/mt7615.1.2G.dat
# sed -i 's/RRMEnable=0/RRMEnable=1/g' package/kernel/mt-drivers/mt_wifi/files/mt7615.1.5G.dat
# sed -i 's/FtSupport=0/FtSupport=1/g' package/kernel/mt-drivers/mt_wifi/files/mt7615.1.2G.dat
# sed -i 's/FtSupport=0/FtSupport=1/g' package/kernel/mt-drivers/mt_wifi/files/mt7615.1.5G.dat
# echo 'WNMEnable=1' >> package/kernel/mt-drivers/mt_wifi/files/mt7615.1.2G.dat
# echo 'WNMEnable=1' >> package/kernel/mt-drivers/mt_wifi/files/mt7615.1.5G.dat
