name: Auto Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        default: 'v23.05.2'
  repository_dispatch:
    types: [Auto Build]

permissions:
  contents: write
  packages: write
  actions: write
  
env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master
  VERBOSE: false
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: full.config
  PRE_FEEDS_UPDATE: 00-feeds-update.sh
  POST_FEEDS_UPDATE: 99-feeds-update.sh
  TZ: Asia/Shanghai

jobs:
  build:
    name: "build openwrt"
    outputs:
      tag: ${{ steps.Get-tag.outputs.tag }}
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set tag from inputs or client payload
      id: Get-tag
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          tag="${{ github.event.inputs.tag }}"
        else
          tag="${{ github.event.client_payload.tag }}"
        fi
        echo "tag=${tag}" >> $GITHUB_OUTPUT

    - name: Clone source code
      run: |
        df -hT $PWD

        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        cd /workdir
          
        git clone $REPO_URL openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        git fetch --all
        git checkout tags/${{ steps.Get-tag.outputs.tag }}

        if [ ${{ env.VERBOSE }} == 'true' ] ; then
          echo "Upstream latest tag: ${{ steps.Get-tag.outputs.tag }}"
          echo "Current released tag: $(awk '/latest/{print $NF; exit}' README.md)"
        fi
        
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo apt-get -qq update --fix-missing
        sudo apt full-upgrade -y

        # https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem#examples_of_package_installations
        # for ubuntu-22.04
        sudo apt-get -y -qq install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget > /dev/null
  
        sudo apt-get -qq autoremove --purge
        sudo apt-get -qq clean
        
        sudo systemctl daemon-reload

    - name: Load custom feeds
      run: |
        cd openwrt
        sh $GITHUB_WORKSPACE/$PRE_FEEDS_UPDATE

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a

    - name: Install feeds
      run: |
        cd openwrt
        ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && cp -R files openwrt/files
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config

    - name: Download package
      id: package
      run: |
        cd openwrt
        # make defconfig
        make clean

        if [ ${{ env.VERBOSE }} == 'true' ] ; then
          grep -i CONFIG_PACKAGE_luci-app .config | grep  -v \# > Plug-in
          grep -i CONFIG_PACKAGE_luci-theme .config | grep  -v \# >> Plug-in
          sed -i '/INCLUDE/d' Plug-in > /dev/null 2>&1
          sed -i 's/CONFIG_PACKAGE_/  * /g' Plug-in
          sed -i 's/=y/\ /g' Plug-in
          sed -i 's/=m/\ /g' Plug-in

          echo
          echo "_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/"
          echo "_/"
          echo "_/ 已选插件列表..."
          echo "_/"
          echo "_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/"
          echo
          cat Plug-in
          echo -e "\n\n\n\n"
          rm -rf Plug-in
        fi
        
    - name: Make download
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Post make download
      run: |
        if [ ${{ env.VERBOSE }} == 'true' ] ; then
          echo
          echo "_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/"
          echo "_/"
          echo "_/ 编译程序修正后的变化 ..."
          echo "_/"
          echo "_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/"
          echo
          diff $GITHUB_WORKSPACE/$CONFIG_FILE openwrt/.config || true
        fi
        
        cd openwrt
        sh $GITHUB_WORKSPACE/$POST_FEEDS_UPDATE
        # if [ ${{ env.VERBOSE }} == 'true' ] ; then
          cd $GITHUB_WORKSPACE
          echo
          echo "_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/"
          echo "_/"
          echo "_/ 脚本程序修正后的变化 ..."
          echo "_/"
          echo "_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/"
          echo
          diff $GITHUB_WORKSPACE/$CONFIG_FILE openwrt/.config || true
        # fi
        
    - name: Compile tools
      id: compile-world
      run: |
        set -e
        cd openwrt

        if [ ${{ env.VERBOSE }} == 'true' ] ; then
          echo
          echo "_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/"
          echo "_/"
          echo "_/ 编译配置列表..."
          echo "_/"
          echo "_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/"
          echo
          cat .config
          echo -e "\n\n\n\n"
        fi
        
        make -j$(nproc)
        
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Organize files
      id: organize
      if: steps.compile-world.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        
        tree .
        
        rm -rf packages
        if [ ${{ env.VERBOSE }} == 'true' ] ; then
          tree .
        fi
        
        mv openwrt-23.05-immortalwrt-ramips-mt7621-phicomm_k2p-initramfs-kernel.bin phicomm_k2p-initramfs-kernel.bin
        mv openwrt-23.05-immortalwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.bin phicomm_k2p-squashfs-sysupgrade.bin
        mv openwrt-23.05-immortalwrt-ramips-mt7621-phicomm_k2p.manifest phicomm_k2p.manifest
        
        if [ ${{ env.VERBOSE }} == 'true' ] ; then
          echo
          echo "_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/"
          echo "_/"
          echo "_/ 待发布文件列表..."
          echo "_/"
          echo "_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/"
          tree .
          echo
        fi
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Debug -> list files before upload to artifact
      if: env.VERBOSE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      run: ls -lah ${{ env.FIRMWARE }}

    - name: Upload binaries to artifact
      if: steps.organize.outputs.status == 'success' && !cancelled()
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: ${{ env.FIRMWARE }}/
        
    - name: Debug -> list files after upload to artifact
      if: env.VERBOSE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      run: ls -lah ${{ env.FIRMWARE }}
    
    - name: Upload binaries to release
      id: release
      if: steps.organize.outputs.status == 'success' && !cancelled()
      uses: svenstaro/upload-release-action@v2
      env:
        TAG: ${{ steps.Get-tag.outputs.tag }}
        DESC: ${{ steps.Get-tag.outputs.tag }}
      with:
        file: ${{ env.FIRMWARE }}/*
        file_glob: true
        tag: ${{ env.TAG }}
        overwrite: true
        body: ${{ env.DESC }}
    
    - name: Remove old Releases
      if: steps.release.outputs.browser_download_url != '' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: dev-drprasad/delete-older-releases@v0.3.4
      with:
        keep_latest: 3
        delete_tags: true

  update-repo:
    needs:
      - build
    runs-on: ubuntu-latest
    name: "update source code"
    env:
      TAG: ${{ needs.build.outputs.tag }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Update source code
        id: update-code
        run: |
          sed -i "s/\(latest.*:\).*/\1 ${{ env.TAG }}/" README.md
          sed -i "s/\(default[[:space:]]*:\).*/\1 '${{ env.TAG }}'/" .github/workflows/build.yml
          
          git checkout --orphan tmp_work
          git branch -D main
          DATE="$(date '+%Y/%m/%d')"
          COMMENT="Build to ${{ env.TAG }} by Github Actions, ${DATE}"

          git branch -m main
          echo "msg=$COMMENT" >> $GITHUB_OUTPUT
          
      - name: Commit & Push changes
        env:
          MSG: ${{ steps.update-code.outputs.msg }}
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ env.MSG }}
          force: true
          
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: "cancelled, skipped, success"
